```{r, message=FALSE}
library(metabaR)
library(dplyr)
library(reshape2)
library(data.table)
```

```{r}
#import data, already motu-aggregated and log-chord transformed
dt_name <- "plants_r2_embl_98"

dt_format <- "_2rep_motuAgg_norm_sp_trait"
dt_format <- "_clean"
```

*Optional: choose if to use freq of detection format*
```{r}
dt <- readRDS(paste("../00_R-repository/",dt_name, dt_format,sep=""))

# aggregate motus
dt_motuAgg <- aggregate_motus(dt, groups=dt$motus$TAXID)

# aggregate pcrs by site, output frequency of detection 
dt_st <- dt_motuAgg
dt_st$pcrs <- left_join(dt_motuAgg$pcrs, dt_motuAgg$samples %>% mutate(sample_id=rownames(.)), by="sample_id")
rownames(dt_st$pcrs) <- rownames(dt_motuAgg$pcrs)
dt_st$pcrs$sample_id <- dt_st$pcrs$site

# load the new 'samples' table: sites
sites<- read.table("../03_metabaR/surfsedi_sites.txt", header=T, sep='\t')
rownames(sites) <- sites$site
dt_st$samples <- sites

# frequency of detection at sites
data <- aggregate_pcrs(dt_st, FUN=FUN_agg_pcrs_prob)
```
  
```{r}
# read modified motus table
library(readxl)
motus_man <- read_xlsx("plant_traits.xlsx", col_names = T, na=c("","NA")) %>% `row.names<-`(.$TAXID)
```


















```{r}
# add traits into motus table
motus_new <- left_join(data$motus, 
                       motus_man %>% select(-c("SCIENTIFIC_NAME",	"family_name",	"genus_name",	"species_name")), 
                       by="TAXID") %>%
  `rownames<-`(.$TAXID)

data$motus <- motus_new
check_metabarlist(data)
```


```{r}
# organise cultivated_IF, Aquatic, alpine into one column 
data$motus <- data$motus %>% mutate(traits = ifelse(alpine %in% c("TRUE","T"), "alpine",
                                                ifelse(Aquatic %in% c("aquatic","T"), "aquatic",
                                                       ifelse(cultivated_IF %in% c("TRUE","T"), "cultivated",
                                                              "others")))) %>%
  mutate(growth_form = ifelse(PlantGrowthForm %in% c("shrub","shrub/tree","tree"), "shrubs & trees",
                              ifelse(PlantGrowthForm=="graminoid", "grass & sedges",
                                     ifelse(PlantGrowthForm=="herb","non-grass herbs", PlantGrowthForm))))
```






```{r}
saveRDS(data, paste("../00_R-repository/",dt_name, "_motuAgg_FoD_trait",sep=""))
```






















